# Generated by Django 3.2.9 on 2022-05-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220522_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
