# Generated by Django 3.2.9 on 2022-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_transaction_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(max_length=255),
        ),
    ]
