# Generated by Django 3.2.9 on 2022-05-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220522_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_to',
        ),
    ]
