# Generated by Django 3.2.9 on 2022-05-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220522_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_to',
            field=models.IntegerField(default=0),
        ),
    ]
