# Generated by Django 3.2.9 on 2022-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220522_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fp',
        ),
        migrations.AddField(
            model_name='transaction',
            name='c1_c14',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='color_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='d1_d15',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_in_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_35_38',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='m1_m3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='m5_m9',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='screen_resolution',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='v1_v339',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
