# Generated by Django 3.2.9 on 2022-05-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220522_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_in_seconds',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='device_info',
        ),
    ]
