# Generated by Django 3.2.9 on 2022-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220522_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='v1_v339',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
