# Generated by Django 3.2.9 on 2022-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_transaction_v1_v339'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='brouser',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='os',
            field=models.CharField(default='', max_length=100),
        ),
    ]
